### NEXT WORD PREDICTOR THROUGH LSTM(LONG SHORT TERM MEMORY)

Importing the dependencies

In [81]:
import os 
import json

import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Embedding , LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Loading dataset

In [82]:
df = pd.read_csv(r"D:\Deep Learning\Long_short_term_memory(LSTM)\IMDB Dataset.csv")

In [83]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [84]:
df.shape

(50000, 2)

In [85]:
df.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [86]:
df.tail(5)

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [87]:
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [88]:
df.replace({"sentiment" : {"positive" : 1, "negative" : 0}},inplace = True)

                                                  review sentiment
0      One of the other reviewers has mentioned that ...         1
1      A wonderful little production. <br /><br />The...         1
2      I thought this was a wonderful way to spend ti...         1
3      Basically there's a family where a little boy ...         0
4      Petter Mattei's "Love in the Time of Money" is...         1
...                                                  ...       ...
49995  I thought this movie did a down right good job...         1
49996  Bad plot, bad dialogue, bad acting, idiotic di...         0
49997  I am a Catholic taught in parochial elementary...         0
49998  I'm going to have to disagree with the previou...         0
49999  No one expects the Star Trek movies to be high...         0

[50000 rows x 2 columns]

In [89]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...         1
1  A wonderful little production. <br /><br />The...         1
2  I thought this was a wonderful way to spend ti...         1
3  Basically there's a family where a little boy ...         0
4  Petter Mattei's "Love in the Time of Money" is...         1

In [90]:
df["sentiment"].value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

spliting Data into Train_test_split

In [91]:
train_data , test_data = train_test_split(df , test_size=0.2,random_state=2)

not spliting data into x_train and Y_train first i'll do preprocessing and then i will split into x_train and Y_train.

In [92]:
print(train_data.shape)
print(test_data.shape)

(40000, 2)
(10000, 2)

Data Preprocessing

In [93]:
# tokenize text data 
tokenizer = Tokenizer(num_words=5000) # convert words into numbers it gives tokes to each & every text
tokenizer.fit_on_texts(train_data["review"])
x_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]),maxlen=200)
x_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]),maxlen=200)

In [94]:
print(x_train)

[[3474   13  847 ...   78  547  166]
 [   0    0    0 ...  105 3444  176]
 [ 133    6  429 ...  143  155 1198]
 ...
 [ 195  117   32 ...   27    4   91]
 [   0    0    0 ...   19   30  125]
 [  38   88 2252 ...   23   30    9]]

In [95]:
print(x_test)

[[   0    0    0 ...   30   29 2207]
 [  19   13  154 ...   11 3764 2469]
 [   0    0    0 ...  443  223   50]
 ...
 [ 321   18  416 ...  196    9   12]
 [   0    0    0 ...  706    2   19]
 [   0    0    0 ...    8   11   19]]

In [96]:
y_train = train_data["sentiment"]
y_test = test_data["sentiment"]

In [97]:
y_train

5478     0
22132    0
33533    1
42605    1
48740    1
        ..
44566    0
30280    0
6637     1
35343    0
23720    0
Name: sentiment, Length: 40000, dtype: object

In [98]:
y_test

23656    0
27442    0
40162    1
8459     1
8051     1
        ..
44231    0
18034    0
33856    0
15906    1
40899    1
Name: sentiment, Length: 10000, dtype: object

In [103]:
y_train = y_train.astype("int32")
y_test = y_test.astype("int32")

### LSTM (LONG SHORT-TERM MEMORY)

In [104]:
# building the model

model = Sequential()
model.add(Embedding(input_dim=5000,output_dim=128,input_length=200))
model.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation="sigmoid"))

c:\Users\hb292\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [105]:
# compile the model
model.compile(optimizer = "adam" , loss="binary_crossentropy",metrics=["accuracy"])

Training the model

In [106]:
model.fit(x_train,y_train,epochs=5,batch_size=64,validation_split=0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 126s 248ms/step - accuracy: 0.7827 - loss: 0.4662 - val_accuracy: 0.8520 - val_loss: 0.3510
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 120s 241ms/step - accuracy: 0.8506 - loss: 0.3540 - val_accuracy: 0.8249 - val_loss: 0.3954
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 122s 243ms/step - accuracy: 0.8718 - loss: 0.3124 - val_accuracy: 0.8654 - val_loss: 0.3185
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 126s 253ms/step - accuracy: 0.8918 - loss: 0.2723 - val_accuracy: 0.8765 - val_loss: 0.3135
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 121s 242ms/step - accuracy: 0.8744 - loss: 0.2975 - val_accuracy: 0.8662 - val_loss: 0.3216

Model Evaluation

In [107]:
loss,accuracy = model.evaluate(x_test,y_test)#now here in x_test it will predict the data and compare with actual data
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 21ms/step - accuracy: 0.8687 - loss: 0.3200
Test Loss: 0.31997931003570557
Test Accuracy: 0.8687000274658203

Building the predictive system

In [ ]:
def predict_sentiment(review):
    sequence = tokenizer.text_to_sequences([review])#tokenizes text data 
    padded_sequence = pad_sequences(sequence,maxlen=200)# tehn padding it
    prediction = model.predict(padded_sequence) # this will give a probability
    sentiment = "positive" if prediction[0][0] > 0.5 else "negative"
    return sentiment

In [ ]:
# example usage